### ISSUE TITLE
Auto brightness

### ISSUE THREAD

**Issue by diggit** [ponces/Poncesify#1]
Hi,
does your module also solve not working display auto brigness or is is working for you? I saw some already closed PR at phhussons' ovelay repo. Do you have some summary xda thread about A40, GSI and so?

**Comment by ponces** [comment]
No, this module has only the following features:
- Add Pixel Launcher and Pixel Themes applications
- Add Pixel Accent Color
- Add Android 10 dark boot animation
- Add Fullscreen Gestures overlay
- Enable applications based on Camera 2 API to record in 3840x2160 resolution
- Replace system font with Google Sans
- Hide Browser2, Camera2, Email, LiveWallpapersPicker, Messaging, Music, QuickSearchBox, QuickStep applications
- Fix top corners
- Fix animation lag
- Fix MTP

I created this module to ease the personalization of phhusson's ROM and add some basic A40 fixes.
I tried without success to add an overlay to fix auto brightness but the fix proved to be more time consuming than I predicted so I gave up.
Nevertheless, it's in the news today that our A40 is already receiving Android 10's update so if Samsung was able to fix this, we will know soon. If not, when I have time, I'll try to fix it again by decompiling the original framework.
